### PR TITLE
Add Async API (.NET 4.0 with Microsoft.Bcl.Async)

### PR DESCRIPTION
**Pull request by arledesma**
Adds Async API
Adds Microsoft.Bcl.Async dependency
Updates version to 1.2.0.0 due to feature add

See #2 for updating to .NET 4.5 and not using Microsoft.Bcl.Async

### CODE REVIEW

**Comment by arledesma** [comment]
The test failed due to MarkMonitor's rate limiting.

**Comment by jsakamoto** [comment]
@arledesma Thank you for your pull request. I'm working now for merge this pull request.

I think, I'll number v.2.x for async version about both of .NET4.5 edition and .NET4.0 edition with Ms.Bcl.Async,
and keep v.1.x for .NET4.0 edition without dependencies of Ms.Bcl.Async to keep backward compatibility.

**Comment by jsakamoto** [comment]
@arledesma I could not complete this task tonight... (in Japan Time Zone)

Today's commits are here: https://github.com/jsakamoto/WhoisClient.NET/commits/improve/packaging-nuget

Please let me more a few days.

**Comment by jsakamoto** [comment]
@arledesma I did it.

http://www.nuget.org/packages/WhoisClient.NET/2.0.0

Thanks.

**Pull request merged**
